"""initial tables

Revision ID: 81313cfb65e7
Revises: 
Create Date: 2026-06-11 23:14:38.129695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81313cfb65e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rl_decision_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_lab_id', sa.Integer(), nullable=True),
    sa.Column('selected_bitrate', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['r_lab_id'], ['remote_lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roi_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_lab_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['r_lab_id'], ['remote_lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_lab_id', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Float(), nullable=True),
    sa.Column('buffer_level', sa.Float(), nullable=True),
    sa.Column('throughput', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['r_lab_id'], ['remote_lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_log')
    op.drop_table('roi_config')
    op.drop_table('rl_decision_log')
    op.drop_table('remote_lab')
    # ### end Alembic commands ###
