"""added image and video urls and removed streaming attribute from the remoteLab table

Revision ID: b073f74f0187
Revises: eb52d8bc71e3
Create Date: 2026-06-23 21:06:08.849075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b073f74f0187'
down_revision = 'eb52d8bc71e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('stream_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
