"""added roi name

Revision ID: f4d72828bfba
Revises: 81313cfb65e7
Create Date: 2026-06-12 19:13:39.826706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d72828bfba'
down_revision = '81313cfb65e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roi_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roi_config', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
